# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anon_Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_text', models.CharField(max_length=200)),
                ('parameter', models.CharField(max_length=200)),
                ('is_missing', models.IntegerField(default=0)),
                ('is_high', models.IntegerField(default=0)),
                ('is_rt', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Anon_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Anon_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_text', models.CharField(max_length=200)),
                ('is_rt', models.IntegerField(default=0)),
                ('parameter', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Anon_Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(verbose_name='Not finished Yet!')),
                ('anon_algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPDP.Anon_Algorithm')),
                ('anon_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPDP.Anon_Model')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_text', models.CharField(max_length=200)),
                ('data_url', models.CharField(max_length=200)),
                ('size', models.IntegerField(default=0)),
                ('qid_index', models.CharField(max_length=200)),
                ('sa_index', models.CharField(max_length=200)),
                ('is_missing', models.IntegerField(default=0)),
                ('is_high', models.IntegerField(default=0)),
                ('is_rt', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='anon_task',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPDP.Data'),
        ),
        migrations.AddField(
            model_name='anon_data',
            name='anon_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPDP.Anon_Model'),
        ),
        migrations.AddField(
            model_name='anon_data',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPDP.Data'),
        ),
        migrations.AddField(
            model_name='anon_data',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPDP.Anon_Task'),
        ),
        migrations.AddField(
            model_name='anon_algorithm',
            name='anon_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPDP.Anon_Model'),
        ),
    ]
