# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('PPDP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anon_Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anon_result', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eval_Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_result', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='anon_data',
            name='result',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anon_task',
            name='parameters',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eval_result',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPDP.Anon_Task'),
        ),
        migrations.AddField(
            model_name='anon_result',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPDP.Anon_Task'),
        ),
    ]
