# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPDP', '0002_auto_20160111_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='anon_task',
            name='task_text',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
