# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 03:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PPDP', '0003_anon_task_task_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anon_result',
            name='task',
        ),
        migrations.RemoveField(
            model_name='anon_task',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='eval_result',
            name='task',
        ),
        migrations.AddField(
            model_name='anon_result',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 12, 3, 35, 11, 651237, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anon_result',
            name='key',
            field=models.CharField(default=datetime.datetime(2016, 1, 12, 3, 35, 37, 564514, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anon_result',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 12, 3, 35, 45, 965051, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anon_task',
            name='result_set',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='eval_result',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 12, 3, 35, 53, 276542, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eval_result',
            name='key',
            field=models.CharField(default=datetime.datetime(2016, 1, 12, 3, 36, 1, 556360, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eval_result',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 12, 3, 36, 4, 492255, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anon_task',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 12, 3, 34, 33, 796077, tzinfo=utc)),
        ),
    ]
