# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 03:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PPDP', '0004_auto_20160112_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anon_result',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='anon_result',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 12, 3, 53, 44, 974977, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='anon_task',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 12, 3, 53, 44, 974074, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eval_result',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 12, 3, 53, 44, 975621, tzinfo=utc)),
        ),
    ]
