# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 11:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PPDP', '0005_auto_20160112_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anon_data',
            name='anon_model',
        ),
        migrations.RemoveField(
            model_name='anon_data',
            name='data',
        ),
        migrations.RemoveField(
            model_name='anon_data',
            name='task',
        ),
        migrations.AddField(
            model_name='anon_result',
            name='anon_algorithm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PPDP.Anon_Algorithm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anon_result',
            name='anon_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PPDP.Anon_Model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anon_result',
            name='data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PPDP.Data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eval_result',
            name='anon_algorithm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PPDP.Anon_Algorithm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eval_result',
            name='anon_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PPDP.Anon_Model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eval_result',
            name='data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PPDP.Data'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anon_result',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 12, 11, 45, 35, 731000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='anon_task',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 12, 11, 45, 35, 730000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eval_result',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 12, 11, 45, 35, 733000, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Anon_Data',
        ),
    ]
