# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 12:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PPDP', '0006_auto_20160112_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='anon_result',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 12, 12, 8, 13, 643000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anon_task',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 12, 12, 8, 16, 506000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anon_result',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 12, 12, 8, 2, 583000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='anon_task',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 12, 12, 8, 2, 582000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eval_result',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 12, 12, 8, 2, 584000, tzinfo=utc)),
        ),
    ]
