# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 14:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PPDP', '0007_auto_20160112_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anon_result',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 15, 14, 19, 10, 78000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='anon_result',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 15, 14, 19, 10, 78000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='anon_task',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 15, 14, 19, 10, 77000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='anon_task',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 15, 14, 19, 10, 77000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eval_result',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 15, 14, 19, 10, 78000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eval_result',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 15, 14, 19, 10, 78000, tzinfo=utc)),
        ),
    ]
