# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('PPDP', '0008_auto_20160115_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anon_algorithm',
            name='parameter',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='anon_result',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='anon_result',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='anon_task',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='anon_task',
            name='parameters',
            field=jsonfield.fields.JSONField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='anon_task',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='anon_task',
            name='task_type',
            field=models.IntegerField(choices=[(0, 'Anon_Task'), (1, 'Eval_Task')], default=0),
        ),
        migrations.AlterField(
            model_name='eval_result',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='eval_result',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
