# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-16 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPDP', '0009_auto_20160119_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='is_cat',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
