# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-27 13:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PPDP', '0010_data_is_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anon_result',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2015, 11, 26, 12, 52, 45, 773000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='anon_task',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2015, 11, 26, 12, 52, 45, 773000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eval_result',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2015, 11, 26, 12, 52, 45, 773000, tzinfo=utc)),
        ),
    ]
