# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-29 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPDP', '0011_auto_20161127_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='anon_task',
            name='is_high',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anon_task',
            name='is_missing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anon_task',
            name='is_rt',
            field=models.IntegerField(default=0),
        ),
    ]
