# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-29 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPDP', '0012_auto_20161130_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='anon_algorithm',
            name='short',
            field=models.CharField(default='', max_length=200),
        ),
    ]
