# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-29 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PPDP', '0014_data_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anon_algorithm',
            name='short',
        ),
    ]
