# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-30 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPDP', '0015_remove_anon_algorithm_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='is_cat',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='data',
            name='qid_index',
            field=models.CharField(max_length=800),
        ),
    ]
